### PR TITLE
feature: Adding nsis binaries with NSIS_CONFIG_LOG=yes

### PR DESCRIPTION
**Pull request by shaluyadav13**
Issue #12 Include the NSIS binaries build with `scons NSIS_CONFIG_LOG=yes` flag. So, that when needed logging capabilities can be switched on by setting LogSet on.
NSIS Special build with logging: https://sourceforge.net/projects/nsis/files/NSIS%203/3.03/nsis-3.03-log.zip/

### CODE REVIEW

**Comment by shaluyadav13** [comment]
@develar Any update on this pull request?

**Comment by develar** [comment]
@shaluyadav13 Please compile with also `NSIS_MAX_STRLEN=8192` and PR will be merged.

**Comment by mweichert** [comment]
Any update on when this will be merged?

**Comment by kodezen** [comment]
Also interested in this as we would like to be able to during the NSIS install. Any update on when this will be merged?

**Comment by phuonghuynh** [comment]
+1

**Comment by mengzhidiguo** [comment]
Any update on when this will be merged?

**Comment by Janealter** [comment]
Any update?

**Comment by Janealter** [comment]
I made PR with NSIS_MAX_STRLEN=8192 https://github.com/electron-userland/electron-builder-binaries/pull/31

**Pull request closed without merging**
