### PR TITLE
Update linux osslsigncode (1.7.1)

### LINKED ISSUE #10: Support to sign MSI in linux
I'm using docker to build and sign `msi` target and getting the following error:
```
Failed
libgsf is not available, msi support is disabled: /usr/src/app/dist/myapp-electron-ia32.msi
```

I see that the msi signing is supported in [`osslsigncode 1.7.1`](https://github.com/develar/osslsigncode/blob/master/ChangeLog) but couldn't find out which version of the binary is included for linux builds. Only that the one in this repo was updated ~2y ago and the one for darwin was updated more recently.

Adding support for it would be building the linux binary https://github.com/develar/osslsigncode and open a PR? Any hints?

Thanks.

### PR DESCRIPTION
**Pull request by yarcub**
Fixes #10 (Support MSI code signing in linux).

Based on https://github.com/sporsh/docker-osslsigncode/blob/master/Dockerfile
It downloads osslsigncode source from sourceforge and builds the binary.
The build script adds the local workdir as a volume and overrides the binary
to commit.
`winCodeSign/linux/build.sh`

Note: This version has libgsf linked as dependency to also support msi signing on linux.

For everyone wanting to sign msi on linux before this is merged, use the binary on this PR and override the signing tool location with the env vars:
```
USE_SYSTEM_SIGNCODE=false
ENV SIGNTOOL_PATH=${osslsigncode_location}
```

### CODE REVIEW

**Comment by ewjordan** [comment]
+1 on getting this reviewed and merged in - as I mention in https://github.com/code-dot-org/browser/pull/47, this workaround was necessary for me to create a signed MSI build on OS X via Docker.

**Comment by develar** [comment]
Thanks a lot that you provide _infrastructure_ instead of just build files.

**Comment by develar** [comment]
>  libgsf linked as dependency

@yarcub Statically? Or libgsf-1-dev is required on user machine?

**Comment by develar** [comment]
[osslsigncode-osslsigncode-e72a1937d1a13e87074e4584f012f13e03fc1d64.zip](https://github.com/electron-userland/electron-builder-binaries/files/1821437/osslsigncode-osslsigncode-e72a1937d1a13e87074e4584f012f13e03fc1d64.zip)

**Comment by develar** [comment]
/home/develar/Desktop/osslsigncode: error while loading shared libraries: libgsf-1.so.114: cannot open shared object file: No such file or directory

So, need to figure out how to build statically.

**Pull request merged**
