### PR TITLE
Add NSIS binaries with NSIS_CONFIG_LOG=yes and NSIS_MAX_STRLEN=8192

### PR DESCRIPTION
**Pull request by Janealter**
I am using nsis 3.04, as in master

### CODE REVIEW

**Comment by Janealter** [comment]
I am using nsis 3.04, as in master

**Comment by Janealter** [comment]
@develar when can you watch this PR?

**Comment by ustun** [comment]
I think the binaries added in this PR have been reverted and/or the newer builds do not have NSIS_CONFIG_LOG=true. Are there any plans to make sure to always use the nsis bins with logging enabled?

**Comment by Janealter** [comment]
@ustun I think they have not been reverted, see the commit history.  Commit ec807af771a341b93d122734a9a1d6d2ae9bf90a doesn't rewrite these binaries.

**Comment by ustun** [comment]
From what I understand, the first time the binaries in this commit appeared is in 3.0.4.2 release.

However, this commit reverts to 3.0.4.1: https://github.com/electron-userland/electron-builder/commit/9c43cc369a764d361d9d9a22d607febd1d451d92

That said, I tried to get install the intermediate commits to get the 3.0.4.2 release and adding LogSet On still fails with the following message: 

```
Error: LogSet specified, NSIS_CONFIG_LOG not defined.
```

**Comment by Janealter** [comment]
@develar what about binaries with logs? This is a pretty necessary thing for developers who write a lot of custom NSIS scripts.

**Comment by ustun** [comment]
Hmm, I am actually on a mac and noticed that the PR did not add a binary of makensis in mac/ folder. Maybe on Windows, we have the logging build already.

So it might be that we need to compile nsis on mac and put that binary in the repo too?

**Comment by Janealter** [comment]
@ustun yes, I added binaries only for Windows

**Comment by ustun** [comment]
@develar I tried to build it on mac to add the mac binary, but apparently the build works for 3.05, but is broken for 3.04 :/.

Note that you need a new homebrew tap to have the logging build.

See: https://github.com/NSIS-Dev/homebrew-makensis/issues/5

See: https://sourceforge.net/p/nsis/bugs/1235/

Maybe we can re-enable 3.05 now that MS has fixes its defender definitions.

**Pull request merged**
